version: "3.9"
services:
  backend:
    build: ./django-rest
    ports:
      - "8000:8000"
    depends_on:
      - database


  frontend:
    build: ./react-app-with-typescript
    ports:
      - "8080:80"
  
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: myP4azzVV04rd
    ports:
      - 5432:5432