# Generated by Django 4.1.7 on 2023-02-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.TextField(max_length=100)),
                ('months', models.IntegerField()),
                ('profileUrl', models.TextField(max_length=3000)),
                ('description', models.TextField(max_length=3000)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
