# Generated by Django 4.1.7 on 2023-02-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_created_at_sub_createdat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='months',
        ),
        migrations.AlterField(
            model_name='sub',
            name='createdAt',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sub',
            name='updatedAt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
